version: '3'
services:
  app:
    build: .
    container_name: "jinseitou_app"
    ports:
      - "3000:3000"
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/jinseitou
      - bundle:/bundle
    volumes:
      - .:/jinseitou
      - tmp-data:/fkg/tmp
      - log-data:/fkg/log
      # exclude volumes
      - /jinseitou/vendor
      - /jinseitou/tmp
      - /jinseitou/log
      - /jinseitou/.git
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build:
      context:  .
      dockerfile: "Dockerfile_node"
    container_name: "jinseitou_front"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/jinseitou/src
      - ./package.json:/jinseitou/package.json
      - ./yarn.lock:/jinseitou/yarn.lock
      - node_modules:/jinseitou/node_modules
    tty: true
    stdin_open: true

  db:
    image: mysql:5.6
    container_name: "jinseitou_db"
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  tmp-data:
  log-data:
  mysql-data:
  bundle:
  node_modules:
