version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          RAILS_ENV: test
          REDIS_HOST: '127.0.0.1'
      - image: circleci/node:12.2.0
      - image: mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    working_directory: ~/jinseitou

jobs:
  bundle_dependencies:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/jinseitou_app/vendor/bundle
      - restore_cache:
          key: v1-bundle{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-bundle-{{ checksum "yarn.lock" }}
          paths:
            - ~/jinseitou_front/node_modules

  test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: DB create
          command: |
            bin/rails db:create
      - run:
          name: DB migration
          command: |
            bin/rails db:migrate
      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - run:
          name: Run tslint
          command: |
            yarn tslint
      - run:
          name: Run prettier
          command: |
            yarn prettier
      - run:
          name: Run rubocop check
          command: bundle exec rubocop
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - bundle_dependencies:
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - bundle_dependencies
