default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: jinseitou_db

development:
  <<: *default
  database: jinseitou_development

test:
  <<: *default
  database: jinseitou_test

production:
  <<: *default
  database: jinseitou_production
  username: jinseitou
  password: <%= ENV['JINSEITOU_DATABASE_PASSWORD'] %>
